[package]
name = "prisma-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
pest = "2.7.4"
pest_derive = "2.7.4"
prisma-diagnostics = { path = "../prisma-diagnostics" }
